### ISSUE TITLE
The installer suddenly reboot at "2 minutes remaining"

### ISSUE THREAD

**Issue by htrung4** [4mitabh/Ideapad_S340#1]
Hello, your ideapad has the same specs as my P53s (except for the dGPU). I follow this guide of RehabMan (https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) using your EFI driver and kext.
I was able to boot to the installer, format the disk using disk Utility, install the catalina into it. But at the "2 minutes remaining", the system suddenly reboot as in this video: https://www.youtube.com/watch?v=K4iYg9XxPeM
 Then, I saw the new installed disk, but when I tried to boot into it, it reboot at "13 minutes remaining". I tried again many times but it stuck at that step. 
Can you provide some help? Thank you and good day.

**Comment by 4mitabh** [comment]
Hey, It might seem like a boot loop, but just let it reboot and continue. 
I've noticed multiple  installation reboots on certain machines, and it eventually goes though.

**Comment by htrung4** [comment]
Hello, thank you for your reply. However, it still reboot repeatedly at "13 minute remaining". I searched for it and there are many people have problem with "AptioMemoryFix.efi". I also tried to use other drivers including "OsxAptioFixDrv-64.efi" and "OcQuirks.efi" but all are the same, continuously reboot at "13 minutes remaining" or something like that. Do you have another solution? Thank you and have a nice weekend.

**Comment by 4mitabh** [comment]
There's no other solution i can think of.
Might want to seek help on :
https://www.tonymacx86.com/threads/guide-lenovo-ideapad-s340-laptop-on-catalina.288003/

**Comment by aruhant** [comment]
Closing stale bug. No new issues have been reported in the latest release.
